apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: partition
spec:
  action: partition
  mode: all
  selector: &nodeSelector
    namespaces:
      - kube-system
    expressionSelectors:
      - key: nodeName
        operator: In
        values:
          - npd-test-worker
          - npd-test-worker3
      - key: app
        operator: In
        values: [node-problem-detector]
  direction: both
